CREATE TABLE `platform_feedback` (
  `id` VARCHAR(191) NOT NULL,
  `kind` VARCHAR(191) NOT NULL DEFAULT 'probleem',
  `title` VARCHAR(191) NULL,
  `message` TEXT NOT NULL,
  `expected` TEXT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'open',
  `priority` VARCHAR(191) NOT NULL DEFAULT 'normaal',
  `pageUrl` TEXT NOT NULL,
  `path` VARCHAR(191) NULL,
  `browserInfo` JSON NULL,
  `reporterId` VARCHAR(191) NULL,
  `reporterName` VARCHAR(191) NULL,
  `reporterEmail` VARCHAR(191) NULL,
  `internalNotes` TEXT NULL,
  `resolvedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `platform_feedback_status_idx` (`status`),
  INDEX `platform_feedback_priority_idx` (`priority`),
  INDEX `platform_feedback_reporterId_idx` (`reporterId`),
  INDEX `platform_feedback_createdAt_idx` (`createdAt`),
  CONSTRAINT `platform_feedback_reporterId_fkey` FOREIGN KEY (`reporterId`) REFERENCES `users`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
