CREATE TABLE `realworks_backup_captures` (
  `id` VARCHAR(191) NOT NULL,
  `source` VARCHAR(191) NULL,
  `capturedAt` DATETIME(3) NULL,
  `receivedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `host` VARCHAR(191) NOT NULL,
  `path` VARCHAR(191) NOT NULL,
  `query` TEXT NULL,
  `url` TEXT NOT NULL,
  `pageUrl` TEXT NULL,
  `method` VARCHAR(191) NULL,
  `status` INTEGER NULL,
  `contentType` VARCHAR(191) NULL,
  `transport` VARCHAR(191) NULL,
  `hints` JSON NULL,
  `requestBodyPreview` LONGTEXT NULL,
  `responseBody` LONGTEXT NULL,
  `responseTruncated` BOOLEAN NOT NULL DEFAULT false,
  `linkText` TEXT NULL,
  `linkTarget` TEXT NULL,
  `onclickPreview` TEXT NULL,
  `popupTarget` VARCHAR(191) NULL,
  `formTarget` TEXT NULL,
  `formName` VARCHAR(191) NULL,
  `formId` VARCHAR(191) NULL,
  `formTrigger` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `rw_capture_source_idx` (`source`),
  INDEX `rw_capture_host_path_idx` (`host`, `path`),
  INDEX `rw_capture_received_idx` (`receivedAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
