'use client';
import {useEffect,useState,useCallback} from 'react';
type Insight={id:string;keyword:string;searches:number;noResults:number;previousSearches:number;state:string;faqId:number|null;note:string|null};
type Data={insights:Insight[];sync:{key:string;lastSuccessAt:string|null;error:string|null}[];faqs:{id:string;title:string;url:string;sourceKey:string}[];periods:{current:string;previous:string}};
const states=[['NEW','Nog beoordelen'],['IMPROVE','Beter vindbaar maken'],['PLANNED','Nieuw onderwerp oppakken'],['COVERED','Afgehandeld'],['IGNORED','Negeren']];
export default function NewsletterInsights({onChange}:{onChange:()=>void}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=useCallback(async()=>{try{const r=await fetch('/api/nieuwsbrief/insights');if(!r.ok)throw new Error('Zoekinzichten niet beschikbaar');setData(await r.json());}catch(e){setError(e instanceof Error?e.message:'Ophalen mislukt');}},[]);
 useEffect(()=>{void load();},[load]);
 async function sync(month=false){setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/nieuwsbrief/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({month,first:month})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Synchroniseren mislukt');const failed=Object.values(d).filter(v=>v&&typeof v==='object'&&'error' in v) as {error:string}[];if(failed.length)setError(failed.map(v=>v.error).join(' '));setMessage(month?(d.month?.data?.message||'Maandconcept voorbereid of bestaande editie geopend.'):'Brongegevens bijgewerkt.');await load();onChange();}catch(e){setError(e instanceof Error?e.message:'Bijwerken mislukt');}finally{setBusy(false);}}
 async function update(row:Insight,patch:Partial<Insight>){try{const r=await fetch('/api/nieuwsbrief/insights',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...row,...patch})});if(!r.ok)throw new Error('Beoordeling opslaan mislukt');await load();}catch(e){setError(e instanceof Error?e.message:'Opslaan mislukt');}}
 return <section className="rounded-lg border border-gray-200 bg-white p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-semibold">Zoekinzichten en onderwerpen</h2><p className="text-sm text-gray-500">Gebruik zoekvragen voor betere antwoorden en nieuwe video’s.</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>sync()} className="rounded border px-3 py-2 disabled:opacity-50">{busy?'Bijwerken…':'Bronnen bijwerken'}</button><button disabled={busy} onClick={()=>sync(true)} className="rounded bg-green-900 px-3 py-2 text-white disabled:opacity-50">Maandconcept voorbereiden</button></div></div>
 {error&&<p role="alert" className="mt-3 text-red-700">{error}</p>}{message&&<p role="status" className="mt-3">{message}</p>}
 <div className="mt-3 flex flex-wrap gap-4 text-xs text-gray-500">{data?.sync.map(s=><span key={s.key}>{s.key}: {s.lastSuccessAt?new Date(s.lastSuccessAt).toLocaleString('nl-NL'):'nog niet bijgewerkt'}{s.error&&<strong className="block text-red-700">{s.error}</strong>}</span>)}</div>
 {data&&<p className="mt-3 text-xs text-gray-500">Laatste 30 volledige dagen: {data.periods.current.replace(',', ' t/m ')}. Vergelijking: {data.periods.previous.replace(',',' t/m ')}. Zoekacties zijn geen unieke personen.</p>}
 <div className="mt-4 space-y-3">{data?.insights.map(row=><div key={row.id} className="grid gap-3 rounded border p-3 md:grid-cols-[1fr_1fr]"><div><strong>{row.keyword}</strong><p className="text-sm">{row.searches} zoekacties · {row.noResults} zonder resultaat · vorige periode {row.previousSearches}</p><select aria-label={`Beoordeling ${row.keyword}`} value={row.state} onChange={e=>update(row,{state:e.target.value})} className="mt-2 rounded border p-2">{states.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div><select aria-label={`Gekoppeld antwoord ${row.keyword}`} value={row.faqId||''} onChange={e=>update(row,{faqId:e.target.value?Number(e.target.value):null})} className="w-full rounded border p-2"><option value="">Geen antwoord gekoppeld</option>{data.faqs.map(f=><option key={f.id} value={f.sourceKey.split(':').pop()}>{f.title}</option>)}</select><input aria-label={`Notitie ${row.keyword}`} defaultValue={row.note||''} onBlur={e=>{if(e.target.value!==(row.note||''))void update(row,{note:e.target.value});}} placeholder="Redactionele notitie" className="mt-2 w-full rounded border p-2"/></div></div>)}</div>
 {data?.insights.length===0&&<p className="mt-4 text-sm text-gray-500">Nog geen geregistreerde zoekvragen. De bronstatus hierboven laat zien of de meting al beschikbaar is.</p>}
 </section>;
}
