CREATE TABLE `agenda_afspraken` (
  `id`                  VARCHAR(191) NOT NULL,
  `systemid`            INTEGER      NOT NULL,
  `agowner`             VARCHAR(191) NULL,
  `agcode`              VARCHAR(191) NULL,
  `agdescr`             VARCHAR(191) NULL,
  `agtype`              VARCHAR(191) NULL,
  `agstatus`            VARCHAR(191) NULL,
  `agbegin`             DATETIME(3)  NULL,
  `agend`               DATETIME(3)  NULL,
  `aglocation`          VARCHAR(191) NULL,
  `agobjcode`           VARCHAR(191) NULL,
  `agrcode`             VARCHAR(191) NULL,
  `relationRelationid`  VARCHAR(191) NULL,
  `employeeEmployeeid`  INTEGER      NULL,
  `medewerkerFullname`  VARCHAR(191) NULL,
  `agmemo`              TEXT         NULL,
  `agintratext`         TEXT         NULL,
  `agallday`            BOOLEAN      NULL,
  `aginactive`          BOOLEAN      NULL,
  `alastupd`            VARCHAR(191) NULL,
  `gcalEventId`         VARCHAR(191) NULL,
  `gcalSyncedAt`        DATETIME(3)  NULL,
  `createdAt`           DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt`           DATETIME(3)  NOT NULL,

  UNIQUE INDEX `agenda_afspraken_systemid_key` (`systemid`),
  INDEX `agenda_afspraken_agbegin_idx` (`agbegin`),
  INDEX `agenda_afspraken_agobjcode_idx` (`agobjcode`),
  INDEX `agenda_afspraken_agowner_idx` (`agowner`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
