CREATE TABLE `ai_call_jobs` (
  `id` VARCHAR(191) NOT NULL,
  `source` VARCHAR(191) NOT NULL DEFAULT 'bezichtiging',
  `agendaAfspraakId` VARCHAR(191) NULL,
  `projectId` VARCHAR(191) NULL,
  `mauticContactId` INTEGER NULL,
  `leadId` VARCHAR(191) NULL,
  `contactName` VARCHAR(191) NULL,
  `contactPhone` VARCHAR(191) NULL,
  `contactEmail` VARCHAR(191) NULL,
  `language` VARCHAR(191) NOT NULL DEFAULT 'nl',
  `propertyTitle` VARCHAR(191) NULL,
  `propertyAddress` VARCHAR(191) NULL,
  `propertyUrl` TEXT NULL,
  `viewingDate` DATETIME(3) NULL,
  `context` JSON NULL,
  `scriptPreview` LONGTEXT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'draft',
  `reviewNotes` TEXT NULL,
  `reviewedBy` VARCHAR(191) NULL,
  `startedBy` VARCHAR(191) NULL,
  `startedAt` DATETIME(3) NULL,
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ai_call_jobs_status_idx` (`status`),
  INDEX `ai_call_jobs_source_idx` (`source`),
  INDEX `ai_call_jobs_agendaAfspraakId_idx` (`agendaAfspraakId`),
  INDEX `ai_call_jobs_projectId_idx` (`projectId`),
  INDEX `ai_call_jobs_mauticContactId_idx` (`mauticContactId`),
  INDEX `ai_call_jobs_leadId_idx` (`leadId`),
  INDEX `ai_call_jobs_createdAt_idx` (`createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ai_call_results` (
  `id` VARCHAR(191) NOT NULL,
  `aiCallJobId` VARCHAR(191) NOT NULL,
  `pbxCallId` VARCHAR(191) NULL,
  `provider` VARCHAR(191) NULL,
  `contextName` VARCHAR(191) NULL,
  `durationSeconds` INTEGER NULL,
  `outcome` VARCHAR(191) NOT NULL DEFAULT 'answered',
  `summary` TEXT NOT NULL,
  `transcript` LONGTEXT NULL,
  `customerQuestions` JSON NULL,
  `detectedOpportunities` JSON NULL,
  `requestedFollowUp` JSON NULL,
  `proposedLinks` JSON NULL,
  `audioNotes` TEXT NULL,
  `qualityScore` INTEGER NULL,
  `mauticWrittenAt` DATETIME(3) NULL,
  `infoEmailQueuedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ai_call_results_aiCallJobId_idx` (`aiCallJobId`),
  INDEX `ai_call_results_pbxCallId_idx` (`pbxCallId`),
  INDEX `ai_call_results_outcome_idx` (`outcome`),
  INDEX `ai_call_results_createdAt_idx` (`createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `follow_up_drafts` (
  `id` VARCHAR(191) NOT NULL,
  `channel` VARCHAR(191) NOT NULL,
  `purpose` VARCHAR(191) NOT NULL,
  `aiCallJobId` VARCHAR(191) NULL,
  `aiCallResultId` VARCHAR(191) NULL,
  `mauticContactId` INTEGER NULL,
  `projectId` VARCHAR(191) NULL,
  `recipientName` VARCHAR(191) NULL,
  `recipientPhone` VARCHAR(191) NULL,
  `recipientEmail` VARCHAR(191) NULL,
  `subject` VARCHAR(191) NULL,
  `body` TEXT NOT NULL,
  `links` JSON NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'draft',
  `createdBy` VARCHAR(191) NOT NULL DEFAULT 'ai',
  `reviewedBy` VARCHAR(191) NULL,
  `reviewedAt` DATETIME(3) NULL,
  `sentAt` DATETIME(3) NULL,
  `deliveryError` TEXT NULL,
  `waConversationId` VARCHAR(191) NULL,
  `waMessageId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `follow_up_drafts_status_idx` (`status`),
  INDEX `follow_up_drafts_channel_idx` (`channel`),
  INDEX `follow_up_drafts_purpose_idx` (`purpose`),
  INDEX `follow_up_drafts_aiCallJobId_idx` (`aiCallJobId`),
  INDEX `follow_up_drafts_aiCallResultId_idx` (`aiCallResultId`),
  INDEX `follow_up_drafts_mauticContactId_idx` (`mauticContactId`),
  INDEX `follow_up_drafts_createdAt_idx` (`createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `ai_link_catalog` (
  `id` VARCHAR(191) NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `url` TEXT NOT NULL,
  `type` VARCHAR(191) NOT NULL,
  `source` VARCHAR(191) NOT NULL DEFAULT 'manual',
  `language` VARCHAR(191) NOT NULL DEFAULT 'nl',
  `intents` JSON NULL,
  `active` BOOLEAN NOT NULL DEFAULT true,
  `wordpressId` INTEGER NULL,
  `wordpressSlug` VARCHAR(191) NULL,
  `wordpressStatus` VARCHAR(191) NULL,
  `aiDescription` TEXT NULL,
  `whatsappTemplate` TEXT NULL,
  `lastSyncedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `ai_link_catalog_type_wordpressId_key` (`type`, `wordpressId`),
  INDEX `ai_link_catalog_type_idx` (`type`),
  INDEX `ai_link_catalog_source_idx` (`source`),
  INDEX `ai_link_catalog_active_idx` (`active`),
  INDEX `ai_link_catalog_wordpressSlug_idx` (`wordpressSlug`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
