CREATE TABLE `realworks_sync_events` (
  `id` VARCHAR(191) NOT NULL,
  `eventType` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'processed',
  `ignoredReason` TEXT NULL,
  `source` VARCHAR(191) NULL,
  `sourceUrl` TEXT NULL,
  `realworksPath` VARCHAR(191) NULL,
  `method` VARCHAR(191) NULL,
  `systemid` VARCHAR(191) NULL,
  `rcode` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `payloadVersion` VARCHAR(191) NULL,
  `extensionVersion` VARCHAR(191) NULL,
  `payloadHash` VARCHAR(191) NULL,
  `matchStrategy` VARCHAR(191) NULL,
  `matchConfidence` INTEGER NULL,
  `payload` JSON NULL,
  `capturedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `realworks_sync_events_payloadHash_key`(`payloadHash`),
  INDEX `realworks_sync_events_eventType_idx`(`eventType`),
  INDEX `realworks_sync_events_status_idx`(`status`),
  INDEX `realworks_sync_events_systemid_idx`(`systemid`),
  INDEX `realworks_sync_events_rcode_idx`(`rcode`),
  INDEX `realworks_sync_events_email_idx`(`email`),
  INDEX `realworks_sync_events_createdAt_idx`(`createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `realworks_sync_quarantine` (
  `id` VARCHAR(191) NOT NULL,
  `reason` TEXT NOT NULL,
  `severity` VARCHAR(191) NOT NULL DEFAULT 'warning',
  `eventType` VARCHAR(191) NULL,
  `source` VARCHAR(191) NULL,
  `sourceUrl` TEXT NULL,
  `realworksPath` VARCHAR(191) NULL,
  `method` VARCHAR(191) NULL,
  `systemid` VARCHAR(191) NULL,
  `rcode` VARCHAR(191) NULL,
  `email` VARCHAR(191) NULL,
  `payloadVersion` VARCHAR(191) NULL,
  `extensionVersion` VARCHAR(191) NULL,
  `payloadHash` VARCHAR(191) NULL,
  `payload` JSON NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'open',
  `resolvedAt` DATETIME(3) NULL,
  `resolutionNote` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `realworks_sync_quarantine_payloadHash_key`(`payloadHash`),
  INDEX `realworks_sync_quarantine_status_idx`(`status`),
  INDEX `realworks_sync_quarantine_severity_idx`(`severity`),
  INDEX `realworks_sync_quarantine_eventType_idx`(`eventType`),
  INDEX `realworks_sync_quarantine_systemid_idx`(`systemid`),
  INDEX `realworks_sync_quarantine_rcode_idx`(`rcode`),
  INDEX `realworks_sync_quarantine_email_idx`(`email`),
  INDEX `realworks_sync_quarantine_createdAt_idx`(`createdAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
