CREATE TABLE `market_objects` (
  `id` VARCHAR(191) NOT NULL,
  `canonicalKey` VARCHAR(191) NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'active',
  `addressRaw` TEXT NULL,
  `street` VARCHAR(191) NULL,
  `houseNumber` VARCHAR(191) NULL,
  `houseNumberAddition` VARCHAR(191) NULL,
  `postcode` VARCHAR(191) NULL,
  `city` VARCHAR(191) NULL,
  `objectKind` VARCHAR(191) NULL,
  `objectSubType` VARCHAR(191) NULL,
  `askingPrice` INTEGER NULL,
  `transactionPrice` INTEGER NULL,
  `rooms` INTEGER NULL,
  `bedrooms` INTEGER NULL,
  `livingArea` INTEGER NULL,
  `plotArea` INTEGER NULL,
  `buildYear` INTEGER NULL,
  `brokerName` VARCHAR(191) NULL,
  `brokerEmail` VARCHAR(191) NULL,
  `primaryImageUrl` TEXT NULL,
  `firstSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastMutationAt` DATETIME(3) NULL,
  `closedAt` DATETIME(3) NULL,
  `deleteAfter` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `market_objects_canonicalKey_key` (`canonicalKey`),
  INDEX `market_object_status_idx` (`status`),
  INDEX `market_object_address_idx` (`postcode`, `houseNumber`, `houseNumberAddition`),
  INDEX `market_object_delete_after_idx` (`deleteAfter`),
  INDEX `market_object_closed_idx` (`closedAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `market_object_sources` (
  `id` VARCHAR(191) NOT NULL,
  `marketObjectId` VARCHAR(191) NOT NULL,
  `source` VARCHAR(191) NOT NULL,
  `sourceObjectId` VARCHAR(191) NULL,
  `sourceUrl` TEXT NULL,
  `confidence` DOUBLE NULL,
  `rawPayload` JSON NULL,
  `firstSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `market_source_object_key` (`source`, `sourceObjectId`),
  INDEX `market_source_market_object_idx` (`marketObjectId`),
  INDEX `market_source_source_idx` (`source`),
  INDEX `market_source_object_idx` (`sourceObjectId`),
  CONSTRAINT `market_object_sources_marketObjectId_fkey` FOREIGN KEY (`marketObjectId`) REFERENCES `market_objects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `market_object_enrichments` (
  `id` VARCHAR(191) NOT NULL,
  `marketObjectId` VARCHAR(191) NOT NULL,
  `source` VARCHAR(191) NOT NULL DEFAULT 'move',
  `status` VARCHAR(191) NOT NULL DEFAULT 'pending',
  `title` VARCHAR(191) NULL,
  `listingText` LONGTEXT NULL,
  `features` JSON NULL,
  `images` JSON NULL,
  `enrichedAt` DATETIME(3) NULL,
  `error` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `market_enrichment_object_source_key` (`marketObjectId`, `source`),
  INDEX `market_enrichment_status_idx` (`status`),
  INDEX `market_enrichment_enriched_idx` (`enrichedAt`),
  CONSTRAINT `market_object_enrichments_marketObjectId_fkey` FOREIGN KEY (`marketObjectId`) REFERENCES `market_objects`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `market_object_tombstones` (
  `id` VARCHAR(191) NOT NULL,
  `marketObjectId` VARCHAR(191) NULL,
  `canonicalKey` VARCHAR(191) NULL,
  `exchangeObjectIds` JSON NULL,
  `status` VARCHAR(191) NOT NULL,
  `addressRaw` TEXT NULL,
  `postcode` VARCHAR(191) NULL,
  `city` VARCHAR(191) NULL,
  `askingPrice` INTEGER NULL,
  `transactionPrice` INTEGER NULL,
  `closedAt` DATETIME(3) NULL,
  `deletedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `reason` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `market_tombstone_canonical_idx` (`canonicalKey`),
  INDEX `market_tombstone_status_idx` (`status`),
  INDEX `market_tombstone_deleted_idx` (`deletedAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
