CREATE TABLE `realworks_object_mutations` (
  `id` VARCHAR(191) NOT NULL,
  `sourceMessageId` VARCHAR(191) NOT NULL,
  `sourceSubject` VARCHAR(191) NULL,
  `sourceDate` DATETIME(3) NULL,
  `receivedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `mutationType` VARCHAR(191) NOT NULL,
  `mutationLabel` VARCHAR(191) NOT NULL,
  `mutationDate` DATETIME(3) NULL,
  `exchangeObjectId` VARCHAR(191) NOT NULL,
  `moveUrl` TEXT NULL,
  `addressRaw` TEXT NULL,
  `street` VARCHAR(191) NULL,
  `houseNumber` VARCHAR(191) NULL,
  `postcode` VARCHAR(191) NULL,
  `city` VARCHAR(191) NULL,
  `objectKind` VARCHAR(191) NULL,
  `objectSubType` VARCHAR(191) NULL,
  `askingPrice` INTEGER NULL,
  `transactionPrice` INTEGER NULL,
  `rooms` INTEGER NULL,
  `bedrooms` INTEGER NULL,
  `livingArea` INTEGER NULL,
  `plotArea` INTEGER NULL,
  `buildYear` INTEGER NULL,
  `brokerName` VARCHAR(191) NULL,
  `brokerEmail` VARCHAR(191) NULL,
  `imageUrl` TEXT NULL,
  `features` JSON NULL,
  `rawText` TEXT NOT NULL,
  `rawHtml` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rw_mutation_message_object_type_key` (`sourceMessageId`, `exchangeObjectId`, `mutationType`),
  INDEX `rw_mutation_object_idx` (`exchangeObjectId`),
  INDEX `rw_mutation_type_idx` (`mutationType`),
  INDEX `rw_mutation_date_idx` (`mutationDate`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `realworks_searchers` (
  `id` VARCHAR(191) NOT NULL,
  `searcherId` VARCHAR(191) NOT NULL,
  `type` VARCHAR(191) NULL,
  `status` VARCHAR(191) NULL,
  `reference` VARCHAR(191) NULL,
  `objectKind` VARCHAR(191) NULL,
  `relationSystemId` VARCHAR(191) NULL,
  `clientName` VARCHAR(191) NULL,
  `clientEmail` VARCHAR(191) NULL,
  `clientPhone` VARCHAR(191) NULL,
  `mauticContactId` INTEGER NULL,
  `priceMin` INTEGER NULL,
  `priceMax` INTEGER NULL,
  `locations` JSON NULL,
  `criteria` JSON NULL,
  `notes` TEXT NULL,
  `raw` JSON NULL,
  `lastSyncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `realworks_searchers_searcherId_key` (`searcherId`),
  INDEX `rw_searcher_status_idx` (`status`),
  INDEX `rw_searcher_type_idx` (`type`),
  INDEX `rw_searcher_relation_idx` (`relationSystemId`),
  INDEX `rw_searcher_mautic_idx` (`mauticContactId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `realworks_search_results` (
  `id` VARCHAR(191) NOT NULL,
  `searcherId` VARCHAR(191) NOT NULL,
  `searchResultsId` VARCHAR(191) NULL,
  `exchangeObjectId` VARCHAR(191) NOT NULL,
  `exchangeObjectEntityType` VARCHAR(191) NULL,
  `searchResultStatus` VARCHAR(191) NULL,
  `matchingPercentage` DOUBLE NULL,
  `dateFound` DATETIME(3) NULL,
  `dateSent` DATETIME(3) NULL,
  `dateViewed` DATETIME(3) NULL,
  `dateContactFormClicked` DATETIME(3) NULL,
  `isLiked` BOOLEAN NULL,
  `objectAddress` VARCHAR(191) NULL,
  `objectCity` VARCHAR(191) NULL,
  `objectPrice` INTEGER NULL,
  `objectUrl` TEXT NULL,
  `matchedCriteria` JSON NULL,
  `nonMatchedCriteria` JSON NULL,
  `raw` JSON NULL,
  `lastSyncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `rw_result_searcher_object_key` (`searcherId`, `exchangeObjectId`),
  INDEX `rw_result_searcher_idx` (`searcherId`),
  INDEX `rw_result_object_idx` (`exchangeObjectId`),
  INDEX `rw_result_sent_idx` (`dateSent`),
  INDEX `rw_result_viewed_idx` (`dateViewed`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `action_opportunities` (
  `id` VARCHAR(191) NOT NULL,
  `sourceType` VARCHAR(191) NOT NULL,
  `sourceKey` VARCHAR(191) NOT NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'open',
  `priority` VARCHAR(191) NOT NULL DEFAULT 'normal',
  `title` VARCHAR(191) NOT NULL,
  `reason` TEXT NOT NULL,
  `suggestedAction` VARCHAR(191) NULL,
  `contactName` VARCHAR(191) NULL,
  `contactEmail` VARCHAR(191) NULL,
  `contactPhone` VARCHAR(191) NULL,
  `mauticContactId` INTEGER NULL,
  `realworksSearcherId` VARCHAR(191) NULL,
  `exchangeObjectId` VARCHAR(191) NULL,
  `objectAddress` VARCHAR(191) NULL,
  `objectCity` VARCHAR(191) NULL,
  `objectPrice` INTEGER NULL,
  `draftStatus` VARCHAR(191) NULL,
  `draftChannel` VARCHAR(191) NULL,
  `draftText` TEXT NULL,
  `draftRequestedAt` DATETIME(3) NULL,
  `draftCompletedAt` DATETIME(3) NULL,
  `taskId` VARCHAR(191) NULL,
  `pickedUpAt` DATETIME(3) NULL,
  `dismissedAt` DATETIME(3) NULL,
  `completedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `action_opportunities_sourceKey_key` (`sourceKey`),
  INDEX `action_opp_status_idx` (`status`),
  INDEX `action_opp_priority_idx` (`priority`),
  INDEX `action_opp_mautic_idx` (`mauticContactId`),
  INDEX `action_opp_object_idx` (`exchangeObjectId`),
  INDEX `action_opp_created_idx` (`createdAt`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
