CREATE TABLE `knowledge_sources` (
  `id` VARCHAR(191) NOT NULL,
  `slug` VARCHAR(191) NOT NULL,
  `title` VARCHAR(191) NOT NULL,
  `sourceType` VARCHAR(191) NOT NULL,
  `authorityRank` INTEGER NOT NULL DEFAULT 50,
  `publisher` VARCHAR(191) NULL,
  `sourceUrl` TEXT NULL,
  `originalFilename` VARCHAR(191) NULL,
  `edition` VARCHAR(191) NULL,
  `publishedAt` DATETIME(3) NULL,
  `effectiveFrom` DATETIME(3) NULL,
  `effectiveUntil` DATETIME(3) NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'ACTIVE',
  `internalOnly` BOOLEAN NOT NULL DEFAULT true,
  `checksum` VARCHAR(191) NULL,
  `notionPageId` VARCHAR(191) NULL,
  `reportTaxateur` VARCHAR(191) NULL,
  `reportAddress` VARCHAR(191) NULL,
  `reportPostcode` VARCHAR(191) NULL,
  `reportCity` VARCHAR(191) NULL,
  `reportPropertyType` VARCHAR(191) NULL,
  `reportBuildYear` INTEGER NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `trustLevel` VARCHAR(191) NULL,
  `validationStatus` VARCHAR(191) NULL,
  `validatedAt` DATETIME(3) NULL,
  `realworksTaxcode` VARCHAR(191) NULL,
  `realworksDossierNumber` VARCHAR(191) NULL,
  `projectId` VARCHAR(191) NULL,
  `supersedesSourceId` VARCHAR(191) NULL,
  `metadata` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `knowledge_sources_slug_key` (`slug`),
  UNIQUE INDEX `knowledge_sources_notionPageId_key` (`notionPageId`),
  UNIQUE INDEX `knowledge_sources_realworksTaxcode_key` (`realworksTaxcode`),
  INDEX `knowledge_sources_sourceType_status_idx` (`sourceType`, `status`),
  INDEX `knowledge_sources_reportPostcode_reportCity_idx` (`reportPostcode`, `reportCity`),
  INDEX `knowledge_sources_reportAddress_idx` (`reportAddress`),
  INDEX `knowledge_sources_projectId_idx` (`projectId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `knowledge_chunks` (
  `id` VARCHAR(191) NOT NULL,
  `sourceId` VARCHAR(191) NOT NULL,
  `section` VARCHAR(191) NULL,
  `fieldKey` VARCHAR(191) NULL,
  `content` LONGTEXT NOT NULL,
  `sanitizedContent` LONGTEXT NOT NULL,
  `position` INTEGER NOT NULL,
  `embedding` LONGBLOB NULL,
  `embeddingModel` VARCHAR(191) NULL,
  `embeddingDimensions` INTEGER NULL,
  `contentHash` VARCHAR(191) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `knowledge_chunks_sourceId_position_key` (`sourceId`, `position`),
  INDEX `knowledge_chunks_fieldKey_idx` (`fieldKey`),
  INDEX `knowledge_chunks_contentHash_idx` (`contentHash`),
  CONSTRAINT `knowledge_chunks_sourceId_fkey` FOREIGN KEY (`sourceId`) REFERENCES `knowledge_sources` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `knowledge_audit_events` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NULL,
  `action` VARCHAR(191) NOT NULL,
  `queryType` VARCHAR(191) NULL,
  `queryHash` VARCHAR(191) NULL,
  `sourceIds` JSON NULL,
  `model` VARCHAR(191) NULL,
  `durationMs` INTEGER NULL,
  `success` BOOLEAN NOT NULL DEFAULT true,
  `error` TEXT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  INDEX `knowledge_audit_events_action_createdAt_idx` (`action`, `createdAt`),
  INDEX `knowledge_audit_events_userId_idx` (`userId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `knowledge_validation_events` (
  `id` VARCHAR(191) NOT NULL,
  `sourceId` VARCHAR(191) NULL,
  `archiveId` VARCHAR(191) NULL,
  `eventType` VARCHAR(191) NOT NULL,
  `matchStatus` VARCHAR(191) NOT NULL,
  `matchedBy` VARCHAR(191) NULL,
  `occurredAt` DATETIME(3) NULL,
  `details` JSON NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `knowledge_validation_events_archiveId_key` (`archiveId`),
  INDEX `knowledge_validation_events_sourceId_idx` (`sourceId`),
  INDEX `knowledge_validation_events_eventType_matchStatus_idx` (`eventType`, `matchStatus`),
  CONSTRAINT `knowledge_validation_events_sourceId_fkey` FOREIGN KEY (`sourceId`) REFERENCES `knowledge_sources` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
