CREATE TABLE `ads_touchpoints` (
  `id` VARCHAR(191) NOT NULL,
  `eventType` VARCHAR(191) NOT NULL,
  `occurredAt` DATETIME(3) NOT NULL,
  `receivedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `dvSessionId` VARCHAR(191) NULL,
  `dvVisitorId` VARCHAR(191) NULL,
  `gclid` VARCHAR(255) NULL,
  `gbraid` VARCHAR(255) NULL,
  `wbraid` VARCHAR(255) NULL,
  `utmSource` VARCHAR(191) NULL,
  `utmMedium` VARCHAR(191) NULL,
  `utmCampaign` VARCHAR(191) NULL,
  `utmAdgroup` VARCHAR(191) NULL,
  `utmTerm` VARCHAR(191) NULL,
  `utmMatchtype` VARCHAR(191) NULL,
  `utmDevice` VARCHAR(191) NULL,
  `utmNetwork` VARCHAR(191) NULL,
  `utmCreative` VARCHAR(191) NULL,
  `pageUrl` TEXT NULL,
  `pagePath` VARCHAR(191) NULL,
  `landingPage` TEXT NULL,
  `referrer` TEXT NULL,
  `sourceLabel` VARCHAR(191) NULL,
  `consentMarketing` VARCHAR(191) NULL,
  `consentAnalytics` VARCHAR(191) NULL,
  `userAgent` TEXT NULL,
  `ipHash` VARCHAR(191) NULL,
  `dedupeKey` VARCHAR(191) NOT NULL,
  `exportedAt` DATETIME(3) NULL,
  `exportBatchId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,

  UNIQUE INDEX `ads_touchpoints_dedupeKey_key`(`dedupeKey`),
  INDEX `ads_touchpoints_eventType_occurredAt_idx`(`eventType`, `occurredAt`),
  INDEX `ads_touchpoints_dvSessionId_idx`(`dvSessionId`),
  INDEX `ads_touchpoints_dvVisitorId_idx`(`dvVisitorId`),
  INDEX `ads_touchpoints_gclid_idx`(`gclid`),
  INDEX `ads_touchpoints_gbraid_idx`(`gbraid`),
  INDEX `ads_touchpoints_wbraid_idx`(`wbraid`),
  INDEX `ads_touchpoints_exportedAt_idx`(`exportedAt`),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
